### ISSUE TITLE
A Incorrect MAC received on packet occur during PuTTY session.

### ISSUE THREAD

**Issue by Aimeast** [Aimeast/FxSsh#10]
It is found a problem when test the #9. PuTTY may throw **Incorrect MAC received on packet** during `shell` session.

**Comment by Aimeast** [comment]
Reproduce

1. Connect via **PuTTY** by default
2. Just run command `dir` in shell and repeat about 5~15 times
3. PuTTY may throw the **Incorrect MAC** ERROR

I dont know why **PuTTY** may received **Incorrect MAC**, but **ssh.exe** looks like OK. Maybe chose a difference encryption algorithm.

**Comment by Aimeast** [comment]
Because **PuTTY** needs to send package `winadj@putty.projects.tartarus.org`, HERE https://tartarus.org/~simon/putty-snapshots/htmldoc/AppendixF.html. Some of synchronization mechanism goes wrong. (send a packet with repeating *outbound packet sequence*)

**Comment by acid2000** [comment]
But a ChannelFailureMessage is sent as the spec says.

I’ve seen this issue with the standard Ubuntu ssh client.

I think it might be related to multiple channels sending data at the same time and the crypto going out of sync

**Comment by Aimeast** [comment]
Hi @acid2000 , I pushed this commit https://github.com/Aimeast/FxSsh/commit/92bb558b5ae59a86493f89483d78f3676781d086#diff-92634550b79326c13fac2679d286573fR374 .

Could you please test it is fixed or not?

**Comment by Aimeast** [comment]
Anyone else found this question still exists?

**Comment by robeving** [comment]
I patched session.cs on my build. Seems to fix the bug / I wasn't able to reproduce the original issue.
