### ISSUE TITLE
Publish new version to NuGet

### ISSUE THREAD

**Issue by cocowalla** [Aimeast/FxSsh#11]
Version [1.0.0 on NuGet](https://www.nuget.org/packages/FxSsh/) is quite old - would be great to release a new version so we can benefit from the changes and fixes that have been made since then.

**Comment by Aimeast** [comment]
Thanks for your ask. I will release and update new NuGet version after fix the #10 .

**Comment by Aimeast** [comment]
new version 1.1.0 released on nuget https://www.nuget.org/packages/FxSsh/1.1.0.
