### ISSUE TITLE
Request method to clear host key interface.

### ISSUE THREAD

**Issue by watsonsong** [Aimeast/FxSsh#16]
The SshServer has AddHostKey method, I want to add a ClearHostKey to support change the host key during the SshServer running. Is it possible?

**Comment by Aimeast** [comment]
Hi, I don't know it is possible or not right now. but at least, hereafter questions should be consider.

1. Public Key Algorithms https://tools.ietf.org/html/rfc4253#section-6.6
2. Key Re-Exchange https://tools.ietf.org/html/rfc4253#section-9

If change host key at runtime is allowed by RFC, a thread-safety and security mechanisms should be taken in.

**Comment by DCNick3** [comment]
I don't think it's possible, as ssh key is somewhat persistent property of ssh server. [SSH-ARCH#4.1](https://tools.ietf.org/html/rfc4251#section-4.1) suggest client to have database associating keys with hosts, so it assumes, that host keys doesn't change.
