### ISSUE TITLE
xshell 服务器发送了一个无效的主机密钥 

### ISSUE THREAD

**Issue by maikebing** [Aimeast/FxSsh#2]
如题

**Comment by Aimeast** [comment]
请补充具体的使用场景。用的什么客户端，如何连接的，启用了什么服务。

**Comment by maikebing** [comment]
由于行业和采购原因， 我只能使用windows，  我想通过这个工具在我的软件集成ssh 服务端， 便于我维护护，我试图通过密钥的连接。 用的 是xshell  。

**Comment by Aimeast** [comment]
FxSsh是针对Git服务端场景设计的，实现了SSH架构中的`exec`服务。连接xshell需要服务端提供`shell`服务支持，目前FxSsh还没有实现`shell`终端功能。

可以参考我当时写的文章了解SSH架构：http://www.cnblogs.com/Aimeast/p/4584540.html

如有兴趣，可以从这里入手，实现shell服务。https://github.com/Aimeast/FxSsh/blob/fddd9675e8fcd817fcfcfc3ba8e629204df58060/FxSsh/Services/ConnectionService.cs#L67-L83

PS: `exec`服务和`shell`服务非常类似，在此基础上只用很少的代价就可实现`shell`服务。

**Comment by maikebing** [comment]
好。 感谢。
