### ISSUE TITLE
Putty support error

### ISSUE THREAD

**Issue by watsonsong** [Aimeast/FxSsh#3]
First, the server can not use the .ppk public key generated by puttygen.
Second, I use the key in the example and use putty connect to it, but I met this error:
`Unknown request type: pty-req.`

It seems the method 'HandleMessage' in file ConnectionService.cs not process pty-req:
`private void HandleMessage(ChannelRequestMessage message)
{
    switch (message.RequestType)
    {
        case "exec":
            var msg = Message.LoadFrom<CommandRequestMessage>(message);
            HandleMessage(msg);
            break;
        default:
            if (message.WantReply)
                _session.SendMessage(new ChannelFailureMessage
                {
                    RecipientChannel = FindChannelByServerId<Channel>(message.RecipientChannel).ClientChannelId
                });
            throw new SshConnectionException(string.Format("Unknown request type: {0}.", message.RequestType));
    }
}
`

**Comment by Aimeast** [comment]
fixed via #9
