### ISSUE TITLE
When terminal windows resize, outputs are weird

### ISSUE THREAD

**Issue by coddoge** [Aimeast/FxSsh#32]
My SSH client is  PuTTY.
When window width added, the output content still wrap line by old width.
When window height added, after output the cursor is no followed to bottom of window, scroll are broken.

**Comment by Aimeast** [comment]
please see lastest adc00fd dev branch readme, `DEMO MiniTerm not support change window size`

**Comment by coddoge** [comment]
I saw `ResizePseudoConsole` in PseudoConsoleApi.cs of MimiTerm.
Try call it on `MiniTerm.Terminal` class, add a method for `ConnectionService.WindowChange` event to call.

It seem works. 

After window width changed, All outputed content will wrap line or unwrap line immediately
After windows height changed, output scroll still ok.

But i don't know it's stability.
When i run a nano.exe (git bash on windows), long line may display incorrect after window resize.
But nested run ssh to real linux, the nano is working fine.

**Comment by Aimeast** [comment]
FxSsh is a implementation for SSH Protocol, provide interface. But the MiniTerm, it just a DEMO and copy from https://github.com/microsoft/terminal/tree/main/samples/ConPTY/MiniTerm, not a part of FxSsh.

MiniTerm has imported `ResizePseudoConsole` API, but not make it public. As for you said, I didn't know how different between `nano.exe` and `linux ssh`.

And the [readme](https://github.com/Aimeast/FxSsh/tree/dev/SshServerLoader/MiniTerm#status) said, `Demonstrates the basic API calls required, but not intended for "real-world" usage.`

**Comment by coddoge** [comment]
Thank you for reply.
