### ISSUE TITLE
Publish version 1.1.2 to NuGet

### ISSUE THREAD

**Issue by cslutgen** [Aimeast/FxSsh#33]
Any interest in publishing a new version to pick up the dev  branch changes submitted after 1.1.1 was released to nuget? There are some good changes that are of interest to us in the handful of changes made after Jan 19, 2019.

**Comment by Aimeast** [comment]
close via tag v1.2 779d79b
published to nuget https://www.nuget.org/packages/FxSsh/1.2.0
