### ISSUE TITLE
any sample for FxSsh.PwAuth

### ISSUE THREAD

**Issue by bruceb85** [Aimeast/FxSsh#34]
Looking for sample ssh server code on FxSsh.PwAuth, do you have any to share?

**Comment by Aimeast** [comment]
just in sample code `void service_Userauth(object sender, UserauthArgs e)` , please lookup `UserauthArgs e` .

**Comment by mikaelliljedahl** [comment]
You can check out the OnUserAuth method in
https://github.com/mikaelliljedahl/freesftpsharp/blob/master/SshServerModule/HostedServer.cs
That sftpsubsystem implementation is built on top of FxSsh so I implemented authentication mechanisms.

**Comment by Aimeast** [comment]
Close inactivity
