### ISSUE TITLE
Unable to negotiate

### ISSUE THREAD

**Issue by ALSULTAN** [Aimeast/FxSsh#35]
Unable to negotiate with 127.0.0.1 port 9999: no matching key exchange method found. Their offer: diffie-hellman-group14-sha1,diffie-hellman-group1-sha1

**Comment by DitchTurtL** [comment]
This is the same as https://github.com/Aimeast/FxSsh/issues/28

Diffie-Hellman Group1 and Group14 have been deprecated. 

On the client OS, you can get past this by configuring SSH to allow the older algo.
In your ./.ssh/config file, add the line *KexAlgorithms +diffie-hellman-group1-sha1*

**Comment by ThatWileyGuy** [comment]
Fixed in #36
