### ISSUE TITLE
Can not connect on Ubuntu anymore

### ISSUE THREAD

**Issue by MrJackSpade** [Aimeast/FxSsh#38]
```
Unable to negotiate with 192.168.12.58 port 22: no matching key exchange method found. Their offer: diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
```

```
OpenSSH_8.9p1 Ubuntu-3ubuntu0.10, OpenSSL 3.0.2 15 Mar 2022
```

**Comment by Aimeast** [comment]
Repeat #37. The new ssh server has updated the key exchange algorithm suite, and the FxSsh algorithm suite is no longer supported. If you want to continue using it, you need to rewrite a new, more secure cryptographic algorithm suite.

However, I don't have the energy to continue to maintain the project, so if you are interested you can continue to develop it for that purpose.

**Comment by Aimeast** [comment]
close via 8119278
