### ISSUE TITLE
no matching host key type found. their offer: ssh-rsa,ssh-dss

### ISSUE THREAD

**Issue by ALSULTAN** [Aimeast/FxSsh#39]
I think than `ssh-rsa,ssh-dss` are obseletes now.

I can fix the issue:
`ssh -v -oHostKeyAlgorithms=+ssh-rsa -m hmac-md5 192.168.247.199
`
but this is not a valid permenant solution

OpenSSH_for_Windows_9.5p1, LibreSSL 3.8.2
debug1: Connecting to 192.168.247.199 [192.168.247.199] port 2222.
debug1: Connection established.
debug1: identity file C:\\Users\\Administrator/.ssh/id_rsa type -1
debug1: identity file C:\\Users\\Administrator/.ssh/id_rsa-cert type -1
debug1: identity file C:\\Users\\Administrator/.ssh/id_ecdsa type -1
debug1: identity file C:\\Users\\Administrator/.ssh/id_ecdsa-cert type -1
debug1: identity file C:\\Users\\Administrator/.ssh/id_ecdsa_sk type -1
debug1: identity file C:\\Users\\Administrator/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file C:\\Users\\Administrator/.ssh/id_ed25519 type -1
debug1: identity file C:\\Users\\Administrator/.ssh/id_ed25519-cert type -1
debug1: identity file C:\\Users\\Administrator/.ssh/id_ed25519_sk type -1
debug1: identity file C:\\Users\\Administrator/.ssh/id_ed25519_sk-cert type -1
debug1: identity file C:\\Users\\Administrator/.ssh/id_xmss type -1
debug1: identity file C:\\Users\\Administrator/.ssh/id_xmss-cert type -1
debug1: identity file C:\\Users\\Administrator/.ssh/id_dsa type -1
debug1: identity file C:\\Users\\Administrator/.ssh/id_dsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_9.5
debug1: Remote protocol version 2.0, remote software version ALSULTAN
debug1: compat_banner: no match: ALSULTAN
debug1: Authenticating to 192.168.247.199:2222 as 'a'
debug1: load_hostkeys: fopen C:\\Users\\Administrator/.ssh/known_hosts: No such file or directory
debug1: load_hostkeys: fopen C:\\Users\\Administrator/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen __PROGRAMDATA__\\ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen __PROGRAMDATA__\\ssh/ssh_known_hosts2: No such file or directory
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: diffie-hellman-group16-sha512
debug1: kex: host key algorithm: (no match)
Unable to negotiate with 192.168.247.199 port 2222: no matching host key type found. Their offer: ssh-rsa,ssh-dss

C:\Users\Administrator>

**Comment by Aimeast** [comment]
> I think than `ssh-rsa,ssh-dss` are obseletes now.

Yeah, you are right. Repeat #37 and #38, see it.

**Comment by ALSULTAN** [comment]
Thanks, but can anyone adapt a new algorithm?
It is sad for this repository to get thrown out. It has been a great one

**Comment by Aimeast** [comment]
close via 8119278

**Comment by ALSULTAN** [comment]
@Aimeast you are THE MAN
