### ISSUE TITLE
Not working dot net core linux

### ISSUE THREAD

**Issue by glmnet** [Aimeast/FxSsh#7]
in Session.SetSocketOptions 
in `_socket.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.DontLinger, true);
`The following exception is thrown:
System.Net.Sockets.SocketException (95): Operation not supported

I got it working by commenting out this line.

dotnet --version gives: 2.1.401

Seems to be a know dotnet issue
https://github.com/dotnet/corefx/issues/28305

**Comment by Aimeast** [comment]
Hi,

Did you test the code `m_ListenSocket.LingerState = new LingerOption(enable: false, seconds: 0)` from your ref dotnet/corefx#28305. If it is work, please send a PR.

**Comment by Aimeast** [comment]
closed via #8
